@port=3000
@host=http://localhost:{{port}}

### GET /
GET {{host}}

### Get all employees
GET {{host}}/employees

### Get all employees
GET {{host}}/employee

### Add this employee
POST {{host}}/employees
Content-Type: application/json

{
    "id": 11, "name": "Bruce Willis"
}

### Add this employee
POST {{host}}/employees
Content-Type: application/json

{
    "id": jas, "name": "Bruce Wayne"
}

### Get specific employee
GET {{host}}/employees/2

### Get nonexistent employee
GET {{host}}/employees/123

### Update specific employee
PUT {{host}}/employees/2
Content-Type: application/json

{
"name": "Replaced"
}

### Update specific employee
PUT {{host}}/employees/17
Content-Type: application/json

{
"name": "Replaced"
}

### Update specific employee
PUT {{host}}/employees/2
Content-Type: application/json

{
"name": Replaced
}

// Post employee 11 between lines 13-14 to see working results of this request
### Delete specific employee
DELETE {{host}}/employees/11

// Press this if you never want to see Mr.3 ever again.
### Delete specific employee
DELETE {{host}}/employees/3