@port=3000
@host=http://localhost:{{port}}

### GET /
GET {{host}}

### Get all employees
GET {{host}}/employees

### Get specific employee
GET {{host}}/employees/2

### Get nonexistent employee
GET {{host}}/employees/123

### Delete specific employee
DELETE {{host}}/employees/1

### Update specific employee
PUT {{host}}/employees/1

### Add this employee
POST {{host}}/employees
Content-Type: application/json

{
    "id": 11, "name": "Bruce Willis"
}

### Add this employee
POST {{host}}/employees
Content-Type: application/json

{
    "id": 12, "name": "Bruce Wayne"
}

### Add this employee
POST {{host}}/employees
Content-Type: application/json

{
    "id": 13, "name": "Bruce Almighty"
}

### Add this employee
POST {{host}}/employees
Content-Type: application/json

{
    "id": 14, "name": "Bruce Banner"
}